import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { ensureInsideProjectRoot, sanitizeSlug } from "./paths";
import type { CliKind } from "./schemas";

export function renderPlanMarkdown(planItems: string[]) {
  return planItems.map((item, index) => `${index + 1}. ${item}`).join("\n") + "\n";
}

export function renderReadme(input: {
  projectName: string;
  idea: string;
  cli: CliKind;
  planItems: string[];
}) {
  return `# ${input.projectName}

Generated by ThinkingAP.

## Idea

${input.idea}

## Plan

${renderPlanMarkdown(input.planItems)}

## Next Step

Run the selected local AI CLI from this repository using the prompt saved at \`.thinkingap/prompt.txt\`.

Selected CLI: ${input.cli}
`;
}

export function prepareProjectFiles(input: {
  idea: string;
  planItems: string[];
  promptText: string;
  projectName: string;
  targetDir: string;
  cli: CliKind;
}) {
  const targetDir = ensureInsideProjectRoot(input.targetDir);
  const thinkingDir = ensureInsideProjectRoot(path.win32.join(targetDir, ".thinkingap"));
  const slug = sanitizeSlug(input.projectName);

  fs.mkdirSync(thinkingDir, { recursive: true });
  fs.writeFileSync(path.win32.join(thinkingDir, "plan.md"), renderPlanMarkdown(input.planItems), "utf8");
  fs.writeFileSync(path.win32.join(thinkingDir, "prompt.txt"), input.promptText, "utf8");
  fs.writeFileSync(
    path.win32.join(targetDir, "README.md"),
    renderReadme({
      projectName: input.projectName,
      idea: input.idea,
      cli: input.cli,
      planItems: input.planItems,
    }),
    "utf8"
  );
  fs.writeFileSync(path.win32.join(targetDir, ".gitignore"), "node_modules/\n.env\n.env*.local\n", "utf8");

  let gitStatus = "initialized";
  try {
    execFileSync("git", ["init"], {
      cwd: targetDir,
      windowsHide: true,
      stdio: "pipe",
    });
  } catch {
    gitStatus = "git_init_failed";
  }

  return {
    name: input.projectName,
    slug,
    targetPath: targetDir,
    gitStatus,
  };
}
